python_preamble:
- import: base64
- import: re
- import: google.appengine.ext.bulkload.transform
- import: google.appengine.ext.bulkload.bulkloader_wizard
- import: google.appengine.ext.db
- import: google.appengine.api.datastore
- import: google.appengine.api.users

transformers:

- kind: Q
  connector: csv
  connector_options:
    encoding: utf-8
    columns: from_header
  property_map:
    - property: __key__
      external_name: key
      export_transform: transform.key_id_or_name_as_string

    - property: created_at
      external_name: created_at
      # Type: Date/Time Stats: 1 properties of this type in this kind.
      import_transform: transform.import_date_time('%Y-%m-%dT%H:%M:%S')
      export_transform: transform.export_date_time('%Y-%m-%dT%H:%M:%S')

    - property: data
      external_name: data
      # Type: Blob Stats: 1 properties of this type in this kind.
      import_transform: transform.blobproperty_from_base64
      export_transform: base64.b64encode

    - property: updated_at
      external_name: updated_at
      # Type: Date/Time Stats: 1 properties of this type in this kind.
      import_transform: transform.import_date_time('%Y-%m-%dT%H:%M:%S')
      export_transform: transform.export_date_time('%Y-%m-%dT%H:%M:%S')


- kind: Run
  connector: csv
  connector_options:
    encoding: utf-8
    columns: from_header
  property_map:
    - property: __key__
      external_name: key
      export_transform: transform.key_id_or_name_as_string

    - property: binary_ref
      external_name: binary_ref
      # Type: String Stats: 855 properties of this type in this kind.

    - property: created_at
      external_name: created_at
      # Type: Date/Time Stats: 855 properties of this type in this kind.
      import_transform: transform.import_date_time('%Y-%m-%dT%H:%M:%S')
      export_transform: transform.export_date_time('%Y-%m-%dT%H:%M:%S')

    - property: currency
      external_name: currency
      # Type: String Stats: 855 properties of this type in this kind.

    - property: balance
      external_name: balance
      # Type: Float Stats: 855 properties of this type in this kind.
      import_transform: transform.none_if_empty(float)

    - property: ended_at
      external_name: ended_at
      # Type: Date/Time Stats: 855 properties of this type in this kind.
      import_transform: transform.import_date_time('%Y-%m-%dT%H:%M:%S')
      export_transform: transform.export_date_time('%Y-%m-%dT%H:%M:%S')

    - property: is_finished
      external_name: is_finished
      # Type: Boolean Stats: 855 properties of this type in this kind.
      import_transform: transform.regexp_bool('true', re.IGNORECASE)

    - property: is_win
      external_name: is_win
      # Type: Boolean Stats: 853 properties of this type in this kind.
      import_transform: transform.regexp_bool('true', re.IGNORECASE)

    - property: parent_run
      external_name: parent_run
      # Type: Key Stats: 411 properties of this type in this kind.
      import_transform: transform.create_foreign_key('Run')
      export_transform: transform.key_id_or_name_as_string

    - property: payout
      external_name: payout
      # Type: Float Stats: 855 properties of this type in this kind.
      import_transform: transform.none_if_empty(float)

    - property: probability
      external_name: probability
      # Type: Float Stats: 343 properties of this type in this kind.
      import_transform: transform.none_if_empty(float)

    - property: profit
      external_name: profit
      # Type: Float Stats: 853 properties of this type in this kind.
      import_transform: transform.none_if_empty(float)

    - property: profit_net
      external_name: profit_net
      # Type: Float Stats: 853 properties of this type in this kind.
      import_transform: transform.none_if_empty(float)

    - property: profit_parent
      external_name: profit_parent
      # Type: Float Stats: 855 properties of this type in this kind.
      import_transform: transform.none_if_empty(float)

    - property: stake
      external_name: stake
      # Type: Float Stats: 855 properties of this type in this kind.
      import_transform: transform.none_if_empty(float)

    - property: stake_net
      external_name: stake_net
      # Type: Float Stats: 247 properties of this type in this kind.
      import_transform: transform.none_if_empty(float)

    - property: stake_parent
      external_name: stake_parent
      # Type: Float Stats: 238 properties of this type in this kind.
      import_transform: transform.none_if_empty(float)

    - property: step
      external_name: step
      # Type: Integer Stats: 855 properties of this type in this kind.
      import_transform: transform.none_if_empty(int)

    - property: time_frame
      external_name: time_frame
      # Type: String Stats: 855 properties of this type in this kind.

    - property: trade_aim
      external_name: trade_aim
      # Type: String Stats: 855 properties of this type in this kind.

    - property: trade_base
      external_name: trade_base
      # Type: String Stats: 855 properties of this type in this kind.

    - property: updated_at
      external_name: updated_at
      # Type: Date/Time Stats: 855 properties of this type in this kind.
      import_transform: transform.import_date_time('%Y-%m-%dT%H:%M:%S')
      export_transform: transform.export_date_time('%Y-%m-%dT%H:%M:%S')

