application: binary-trading
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: 1.5

handlers:
- url: /remoteapi.*
  script: google.appengine.ext.remote_api.handler.application
  login: admin

- url: /static
  static_dir: static

- url: /cron/.*
  script: config.wsgi.application
  login: admin

- url: /.*
  script: config.wsgi.application


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^/.idea/.*
- .*less$
- .*map$
- bulkloader/.*