application: binary-trading
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: off

inbound_services:
- warmup

libraries:
- name: django
  version: 1.5

handlers:
#- url: /vendor
#  static_dir: vendor

#- url: /assets
#  static_dir: assets

- url: /cron/.*
  script: config.wsgi.application
  login: admin

- url: /.*
  script: config.wsgi.application


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^/.idea/.*