# Generated by Django 3.2.5 on 2021-07-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('slug', models.CharField(max_length=50)),
                ('added_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapped_at', models.DateField(unique=True)),
                ('href', models.CharField(max_length=55)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('max_supply', models.IntegerField()),
                ('circulating_supply', models.IntegerField()),
                ('total_supply', models.IntegerField()),
                ('price', models.FloatField()),
                ('volume_24h', models.FloatField()),
                ('change_7d', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='mvix.cryptocurrency')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='mvix.snapshot')),
            ],
            options={
                'unique_together': {('snapshot', 'cryptocurrency', 'rank')},
            },
        ),
    ]
