# Generated by Django 3.2.5 on 2021-07-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='max_supply',
            field=models.IntegerField(null=True),
        ),
    ]
